imports:
    - { resource: 'factories/cart.yml' }
    - { resource: 'factories/product.yml' }

services:
    coreshop.api.factory.price_view:
        class: CoreShop\Bundle\ApiBundle\ViewFactory\PriceViewFactory
        arguments:
            - '%coreshop.api.view_model.price.class%'

