services:
    CoreShop\Bundle\ApiBundle\ViewRepository\CartViewRepositoryInterface: '@CoreShop\Bundle\ApiBundle\ViewRepository\CartViewRepository'
    CoreShop\Bundle\ApiBundle\ViewRepository\CartViewRepository:
        arguments:
            - '@coreshop.repository.cart'
            - '@CoreShop\Bundle\ApiBundle\ViewFactory\Cart\CartViewFactoryInterface'

    CoreShop\Bundle\ApiBundle\ViewRepository\CartItemViewRepositoryInterface: '@CoreShop\Bundle\ApiBundle\ViewRepository\CartItemViewRepository'
    CoreShop\Bundle\ApiBundle\ViewRepository\CartItemViewRepository:
        arguments:
            - '@coreshop.repository.cart_item'
            - '@CoreShop\Bundle\ApiBundle\ViewFactory\Cart\CartItemViewFactoryInterface'
