imports:
    - { resource: "services/applicators.yml" }
    - { resource: "services/contexts.yml" }
    - { resource: "services/command_handlers.yml" }

services:
    CoreShop\Bundle\ApiBundle\DataTransformer\OrderTokenAwareInputCommandDataTransformer:
        tags:
            - { name: coreshop.api.command_data_transformer }
