imports:
    - { resource: 'services/factories.yml' }
    - { resource: 'services/repositories.yml' }
    - { resource: 'services/handlers.yml' }
    - { resource: 'services/api_platform.yml' }
    - { resource: 'services/security/voters.yml' }

services:
    CoreShop\Bundle\ApiBundle\PropertyInfo\PhpDocExtractor:
        arguments:
            - '@property_info.php_doc_extractor'
        tags:
            - { name: property_info.type_extractor }
