#coreshop_api_pickup_cart:
#    path: /carts
#    methods: [POST]
#    defaults:
#        _controller: coreshop.api.controller.cart.pickup_action
#
coreshop_api_cart_summary:
    path: /carts/{id}
    methods: [GET]
    defaults:
        _controller: coreshop.api.controller.cart.summarize_action
#
#coreshop_api_add_to_new_cart:
#    path: /carts/new/items
#    methods: [POST]
#    defaults:
#        _controller: coreshop.api.controller.cart.put_item_to_cart_action
#
#coreshop_api_add_to_cart:
#    path: /carts/{token}/items
#    methods: [POST]
#    defaults:
#        _controller: coreshop.api.controller.cart.put_item_to_cart_action
#
#coreshop_api_add_multiple_items_to_new_cart:
#    path: /carts/new/multiple-items
#    methods: [POST]
#    defaults:
#        _controller: coreshop.api.controller.cart.put_items_to_cart_action
#
#coreshop_api_add_multiple_items_to_cart:
#    path: /carts/{token}/multiple-items
#    methods: [POST]
#    defaults:
#        _controller: coreshop.api.controller.cart.put_items_to_cart_action
#
#coreshop_api_drop_cart:
#    path: /carts/{token}
#    methods: [DELETE]
#    defaults:
#        _controller: coreshop.api.controller.cart.drop_cart_action
#
#coreshop_api_change_item_quantity:
#    path: /carts/{token}/items/{id}
#    methods: [PUT]
#    defaults:
#        _controller: coreshop.api.controller.cart.change_item_quantity_action
#
#coreshop_api_remove_item_from_cart:
#    path: /carts/{token}/items/{id}
#    methods: [DELETE]
#    defaults:
#        _controller: coreshop.api.controller.cart.remove_item_from_cart_action
#
#coreshop_api_estimated_shipping_cost:
#    path: /carts/{token}/estimated-shipping-cost
#    methods: [GET]
#    defaults:
#        _controller: coreshop.api.controller.cart.estimate_shipping_cost_action
#
#coreshop_api_add_coupon_to_cart:
#    path: /carts/{token}/coupon
#    methods: [PUT]
#    defaults:
#        _controller: coreshop.api.controller.cart.add_coupon_action
#
#coreshop_api_remove_coupon_to_cart:
#    path: /carts/{token}/coupon
#    methods: [DELETE]
#    defaults:
#        _controller: coreshop.api.controller.cart.remove_coupon_action
