#coreshop_api_category_show_details:
#    path: /categories/{id}
#    methods: [GET]
#    defaults:
#        _controller: coreshop.api.controller.taxon.show_taxon_details_action
#
#coreshop_api_categories_show_tree:
#    path: /categories/
#    methods: [GET]
#    defaults:
#        _controller: coreshop.api.controller.taxon.show_taxon_tree_action
