#coreshop_api_me:
#    path: /me
#    methods: [GET]
#    defaults:
#        _controller: coreshop.api.controller.customer.logged_in_customer_details_action
#
#coreshop_api_update_customer:
#     path: /me
#     methods: [PUT]
#     defaults:
#        _controller: coreshop.api.controller.customer.update_customer_action
