#coreshop_api_register:
#    path: /register
#    methods: [POST]
#    defaults:
#        _controller: coreshop.api.controller.customer.register_customer_action
#
#coreshop_api_resend_verification_token:
#    path: /resend-verification-link
#    methods: [POST]
#    defaults:
#        _controller: coreshop.api.controller.customer.resend_verification_token_action
#
#coreshop_api_user_verification:
#    path: /verify-account
#    methods: [GET, POST, PUT]
#    defaults:
#        _controller: coreshop.api.controller.customer.verify_account_action
#
#coreshop_api_reset_password:
#    path: /request-password-reset
#    methods: [PUT]
#    defaults:
#        _controller: coreshop.api.controller.customer.request_password_resetting_action
#
#coreshop_api_password_reset:
#    path: /password-reset/{token}
#    methods: [PUT]
#    defaults:
#        _controller: coreshop.api.controller.customer.reset_password
