CoreShop\Bundle\ApiBundle\ViewModel\ProductView:
    attributes:
        id:
            groups: ['product:item:get', 'cart_summary:item:get', 'cart_item:item:get']
        name:
            groups: ['product:item:get', 'cart_summary:item:get', 'cart_item:item:get']
        description:
            groups: ['product:item:get', 'cart_summary:item:get', 'cart_item:item:get']
        shortDescription:
            groups: ['product:item:get', 'cart_summary:item:get', 'cart_item:item:get']
        images:
            groups: ['product:item:get', 'cart_summary:item:get', 'cart_item:item:get']
        retailPrice:
            groups: ['product:item:get', 'cart_summary:item:get', 'cart_item:item:get']
        discountPrice:
            groups: ['product:item:get', 'cart_summary:item:get', 'cart_item:item:get']
        discount:
            groups: ['product:item:get', 'cart_summary:item:get', 'cart_item:item:get']
        price:
            groups: ['product:item:get', 'cart_summary:item:get', 'cart_item:item:get']
