resources:
    '%coreshop.api.view_model.product.class%':
        collectionOperations: []
        itemOperations:
            get:
                path: '/product/{id}'
                requirements:
                    id: '\d+'
        graphql:
            item_query:
        properties:
            id:
                identifier: true
