security:
    firewalls:
        coreshop_api:
            stateless: true
            anonymous: true
            pattern: ^/coreshop-api-platform/
            provider: coreshop_customer
            json_login:
                check_path: /coreshop-api-platform/authentication_token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
