CoreShop\Bundle\ApiBundle\Command\Cart\ChangeItemQuantityInCart:
    attributes:
        orderItemId:
            groups:
                - coreshop_cart:change_quantity
        quantity:
            groups:
                - coreshop_cart:change_quantity

