services:
    CoreShop\Bundle\ApiBundle\ViewFactory\Cart\CartItemViewFactoryInterface: '@CoreShop\Bundle\ApiBundle\ViewFactory\Cart\CartItemViewFactory'
    CoreShop\Bundle\ApiBundle\ViewFactory\Cart\CartItemViewFactory:
        arguments:
            - '%coreshop.api.view_model.cart_item.class%'
            - '@CoreShop\Bundle\ApiBundle\ViewFactory\Product\ProductViewFactoryInterface'

    CoreShop\Bundle\ApiBundle\ViewFactory\Cart\CartViewFactoryInterface: '@CoreShop\Bundle\ApiBundle\ViewFactory\Cart\CartViewFactory'
    CoreShop\Bundle\ApiBundle\ViewFactory\Cart\CartViewFactory:
        arguments:
            - '%coreshop.api.view_model.cart_summary.class%'
            - '@CoreShop\Bundle\ApiBundle\ViewFactory\Cart\CartItemViewFactoryInterface'

